
version: 2

models:
  - name: silver_service_requests
    description: "A first dbt model"
    columns:
      - name: id_service_request
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null