    SELECT 
        unique_key,
        created_date,
        closed_date,
        agency,
        agency_name,
        complaint_type,
        descriptor,
        location_type,
        incident_zip,
        incident_address,
        street_name,
        cross_street_1,
        cross_street_2,
        intersection_street_1,
        intersection_street_2,
        address_type,
        city,
        landmark,
        status,
        resolution_description,
        resolution_action_updated_date,
        community_board,
        bbl,
        borough,
        x_coordinate_state_plane,
        y_coordinate_state_plane,
        open_data_channel_type,
        park_facility_name,
        park_borough,
        
        JSON_EXTRACT_STRING(location, '$.latitude')::FLOAT AS latitude,
        JSON_EXTRACT_STRING(location, '$.longitude')::FLOAT AS longitude,
        JSON_EXTRACT_STRING(location, '$.human_address.address') AS address,
        JSON_EXTRACT_STRING(location, '$.human_address.city') AS addr_city,
        JSON_EXTRACT_STRING(location, '$.human_address.state') AS addr_state,
        JSON_EXTRACT_STRING(location, '$.human_address.zip') AS addr_zip,
        
        bridge_highway_name,
        bridge_highway_direction,
        bridge_highway_segment,
        facility_type,
        vehicle_type,
        due_date,
        taxi_pick_up_location,
        road_ramp,
        taxi_company_borough
        
    FROM raw_table