CREATE TABLE bronze_service_requests (
    unique_key INTEGER,
    created_date TIMESTAMP,
    closed_date TIMESTAMP,
    agency VARCHAR(50),
    agency_name VARCHAR(255),
    complaint_type VARCHAR(255),
    descriptor VARCHAR(255),
    location_type VARCHAR(255),
    incident_zip INTEGER,
    incident_address VARCHAR(255),
    street_name VARCHAR(255),
    cross_street_1 VARCHAR(255),
    cross_street_2 VARCHAR(255),
    intersection_street_1 VARCHAR(255),
    intersection_street_2 VARCHAR(255),
    address_type VARCHAR(50),
    city VARCHAR(100),
    landmark VARCHAR(255),
    status VARCHAR(100),
    resolution_description TEXT,
    resolution_action_updated_date TIMESTAMP,
    community_board VARCHAR(100),
    bbl BIGINT,
    borough VARCHAR(50),
    x_coordinate_state_plane INTEGER,
    y_coordinate_state_plane INTEGER,
    open_data_channel_type VARCHAR(100),
    park_facility_name VARCHAR(255),
    park_borough VARCHAR(50),
    latitude NUMERIC(10, 7),
    longitude NUMERIC(10, 7),
    address VARCHAR(255),
    addr_city VARCHAR(100),
    addr_state VARCHAR(20),
    addr_zip VARCHAR(20),
    bridge_highway_name VARCHAR(255),
    bridge_highway_direction VARCHAR(50),
    bridge_highway_segment VARCHAR(100),
    facility_type VARCHAR(100),
    vehicle_type VARCHAR(100),
    due_date TIMESTAMP,
    taxi_pick_up_location VARCHAR(255),
    road_ramp VARCHAR(100),
    taxi_company_borough VARCHAR(100)
);